### ISSUE TITLE
Symbol size in interactive plot

### ISSUE THREAD

**Issue by jmdkastro** [camelot-project/frontend#101]
- [ ] 1. It would be nice to add a line to the legend indicating the symbol size for 100-pc clouds.
- [ ] 2. The symbol size should have a floor on top of which the changing scale is added. For the current default limits, Cara's data point at log{Sigma,sigma} = {3.8,0.08} is a single pixel and therefore almost invisible.

**Comment by e-koch** [comment]
For point 1, we could make the example size symbols shown adjustable based on the max/min sizes. The default could be to continue to show three points rounded to the nearest powers of 10.

The second point relates to the conversion between the physical size and the pixel size in the image, which is also needed for #48.

**Comment by e-koch** [comment]
Fixed in #108
