### ISSUE TITLE
Weekly Digest/Progress Summary up to June 2

### ISSUE THREAD

**Issue by jimdale** [camelot-project/frontend#105]
DIGEST WEEK 2:

Database:
(i) New data tables from MarkSwinbank, LisaWei, AdamGinsburg, ErikRosolowsky, 
(ii) Persistent error with the database sometimes apparently being updated even when the submission form throws an error solved (I think)

Webpage:
(i) Bugfix added to deal gracefully with inadmissible characters in column names
(ii) Useful error page for bad commits created
(iii) Bugfix added to solve inability to download query results
(iv) Use of the Inspector in Chrome/Safari/Firefox highlighted for debugging js errors

Plotting:
(i) I experimented with computing, for a set of simulated tracks, an 'average' track which can be over-plotted onto the contours as a line with an arrowhead to show the direction of time:

![simulation_tracks](https://cloud.githubusercontent.com/assets/8014225/7959837/9b0e35de-09fc-11e5-8e8f-3ec8dcc603f0.png)

**Comment by agianne** [comment]
The colourscale plus arrow seems sweet!

**Comment by e-koch** [comment]
Cool! We can attach the hover tool to the line/arrowhead to represent the whole sim.

**Comment by keflavich** [comment]
Moved to wiki: https://github.com/camelot-project/frontend/wiki/Weekly-Digest-%232
