### ISSUE TITLE
Small text/example about the file format on the first upload page

### ISSUE THREAD

**Issue by bcommerc** [camelot-project/frontend#116]
On the first upload page, there is no information about the accepted file formats. Maybe just show a small example of what can be uploaded.

**Comment by keflavich** [comment]
Good idea.  @bcommerc, could you start by adding a small blurb, i.e. a little text saying "many file formats are accepted, e.g. csv, ... The required columns are those in the Query Form".  We'll want to link this to the Help page once that's ready (https://github.com/camelot-project/frontend/issues/114)

**Comment by ltesti** [comment]
This one is closed with https://github.com/camelot-project/frontend/pull/140
