### ISSUE TITLE
Download PNG button

### ISSUE THREAD

**Issue by jmdkastro** [camelot-project/frontend#119]
At query time, a PNG of the plot is generated. We need a download PNG button on the plot page.

After addressing issue #118 in its entirety, a click on query will then allow the user to download an exact copy of the plot they just made.

**Comment by keflavich** [comment]
@e-koch can you take this?

**Comment by e-koch** [comment]
@keflavich  Yup. I'm on it.

**Comment by keflavich** [comment]
related to #58

**Comment by e-koch** [comment]
Addressed in #130
