### ISSUE TITLE
Set alpha values in legend

### ISSUE THREAD

**Issue by e-koch** [camelot-project/frontend#124]
This should be set in our own plotting script. I think `alpha_unsel` and `alpha_sel` just need to be specified when creating the legend.

**Comment by keflavich** [comment]
Related to #123: adjustable alpha within the plot would be awesome; I'm not sure if that's what you're suggesting here?

**Comment by e-koch** [comment]
No, this would just be setting what the alpha of enabled/disabled points in the plot should be.

We may be able to do the adjustable alpha with only matplotlib, if the mpld3 legend doesn't default the existing points back to the `alpha_sel` value.

**Comment by agianne** [comment]
@keflavich @e-koch I can look into this. For now, I would add a separate field in the query form asking for the transparency of the points, and then we can build from there, if you are ok with this.

**Comment by e-koch** [comment]
@agianne @keflavich - I think we're discussing different things in this issue now. @agianne I think you addressed what I was talking about in #127 already, so I'm going to close this. 

Let's move the discussion over to #123
