### ISSUE TITLE
ErikRosolowsky needs updating

### ISSUE THREAD

**Issue by jmdkastro** [camelot-project/frontend#128]
The ErikRosolowsky IsGalactic tag is set to True but should be False.

**Comment by jmdkastro** [comment]
@e-koch This is probably a quick fix for you, so I've assigned you -- please feel free to decline :-)

**Comment by e-koch** [comment]
Whoops. @jmdkastro Thanks for catching this!

**Comment by e-koch** [comment]
Addressed [here](https://github.com/camelot-project/database/pull/97), so I'm going to close this.
