### ISSUE TITLE
Empty query results in error

### ISSUE THREAD

**Issue by jmdkastro** [camelot-project/frontend#129]
When he selection criteria in the query form imply that no data is selected for display, the server returns an error.

For instance, this:
![screen shot 2015-06-17 at 14 17 32 pm](https://cloud.githubusercontent.com/assets/12392015/8206634/b0d1d0ba-14fb-11e5-94f4-fe92841e97e5.png)

Leads to this:
![screen shot 2015-06-17 at 14 17 39 pm](https://cloud.githubusercontent.com/assets/12392015/8206639/c26603dc-14fb-11e5-9ad7-bacb85f8943d.png)

**Comment by keflavich** [comment]
fixed:
![image](https://cloud.githubusercontent.com/assets/143715/8278809/495be88e-18c6-11e5-9ae8-91d995f841fa.png)
by #138
