### ISSUE TITLE
Symbols don't appear correctly in downloaded plot

### ISSUE THREAD

**Issue by snlongmore** [camelot-project/frontend#131]
I queried the database and then tried to download the resulting plot as a PNG. As you'll see from the image below, the symbols in the axis lables are not formatted correctly. 

Oh, and I guess the fact that the legend is missing is a feature and not a bug ;-) It would potentially make the plot too unwieldy with lots of datasets, right?

![output_sigma_sigma_r_20150618134315842010](https://cloud.githubusercontent.com/assets/12394899/8232750/eb68492e-15c9-11e5-9957-8ac2e75df33a.png)

**Comment by e-koch** [comment]
I think this is a quick fix (hopefully).

**Comment by e-koch** [comment]
Addressed in #134.
