### ISSUE TITLE
gitignore should include created folders in static

### ISSUE THREAD

**Issue by e-koch** [camelot-project/frontend#39]

**Comment by keflavich** [comment]
I think with the new framework this is no longer relevant.  `uploads/` and `database/` are both submodules now.  Could you close this if you agree @e-koch ?

**Comment by e-koch** [comment]
@keflavich -- I agree for the submodules, but I think the folders created for plots and table within static should be ignored. These are only going to be created if the server is run locally and ignoring will avoid any accidental committing.

**Comment by keflavich** [comment]
Solved by #82
