### ISSUE TITLE
Mouseover text shouldn't be shown for hidden points in plot

### ISSUE THREAD

**Issue by scog1234** [camelot-project/frontend#56]
In the interactive plot, it's possible to hide some or all of the different data sets by clicking on the box next to the username (which is a nice feature, by the way). However, the mouseover text still shows up for points that have been hidden this way, which is very confusing.

**Comment by e-koch** [comment]
This one will be a bit more work to fix up. I imagine we will have to write our own mpld3 plugin that accommodates the legend and hover classes.

**Comment by e-koch** [comment]
Number 4 in #23 should also be addressed while fixing this.

**Comment by agianne** [comment]
I had a look at the current plugin, we should find a way to redefine the list of elements to exclude hidden datapoints.

**Comment by agianne** [comment]
I fixed the plugin so that it doesn't show the label if the points are hidden. Will try a pull request tomorrow.

**Comment by agianne** [comment]
I have updated the pull request to include this feature: jakevdp/mpld3#291
My two lines of code are not very "clean", as I am by no means an expert of JS, if you have ideas or suggestions just let me know!

**Comment by e-koch** [comment]
This is now fixed in mpld3: https://github.com/jakevdp/mpld3/pull/299
