### ISSUE TITLE
Save current view of interactive plot and table of that data

### ISSUE THREAD

**Issue by e-koch** [camelot-project/frontend#58]
From #23 - @jimdale :
It would be very cool if there was a button you cloud click on the interactive plot page which makes 
(i) a hardcopy of whatever is in the interactive window
(ii) an ascii file of that data too

**Comment by jmdkastro** [comment]
@e-koch @jimdale I added a hardcopy of the table this morning, but it is not live yet because of a big list of conflicts in the merge (see #54). Adam has been working on the merge and this should be ready soon. Adding a hardcopy of the figure may require some more thought.

**Comment by keflavich** [comment]
#54 is merged and closed now

**Comment by e-koch** [comment]
Addressed in #130
