### ISSUE TITLE
Add source link to database entries

### ISSUE THREAD

**Issue by jmdkastro** [camelot-project/frontend#61]
Early in the week, a main goal was to have an ADS link, DOI link, or email address associated with each data entry, which could possibly be clicked in Eric's plot pop-up.

Given the guaranteed long-term accessibility, we should focus on including ADS links (or a DOI link to the dataset if no paper exists). The entry can be the ADS ID, and the plotting/pop-up code can then complete the URL.

**Comment by e-koch** [comment]
Relates to #35

**Comment by scog1234** [comment]
Question: will this be optional, or do we want to require this by preventing users from uploading data unless they specify a valid ADS ID?

**Comment by jimdale** [comment]
I think requiring an ADS ID would serve as a form of quality assurance so I'm inclined to require it. Are there circumstances where it would be very beneficial to have unpublished data in the database?

**Comment by keflavich** [comment]
I think requiring an ADS ID is reasonable, at least for now.  Perhaps we could default to 'unpublished', though, to provide some flexibility?

**Comment by jimdale** [comment]
We could do that - it would mean we have to have another button on the query form in case people want plots with only published data, though.

**Comment by keflavich** [comment]
That's not a bad idea.  We will require a DOI, though - if there is no link to a permanent data source, we should reject.

**Comment by jimdale** [comment]
Yes, that sounds like the way forward .

**Comment by jmdkastro** [comment]
So just to confirm: we will _not_ add a "published data only" checkbox on the query form, as we will only be accepting published data. So the upload form should check for a valid ADS ID or DOI (perhaps through two text boxes, checking if at least one has a valid (!) entry).

**Comment by keflavich** [comment]
@jmdkastro that's not quite what I meant.  I was thinking we _would_ accept unpublished data, in the sense of not published in an ADS-identified article, but require that the data set has at minimum a DOI.  Perhaps this deserves further discussion via e-mail?

**Comment by jmdkastro** [comment]
That's exactly what I mean, sorry for my ambiguous phrasing. In a way, ADS or DOI are both "published", but we can nonetheless add an "unpublished" (DOI only) and "published" (ADS and possibly also DOI) checkbox just like for sim/obs and gal/exgal. Of course, this will require an extra column in the database.

**Comment by keflavich** [comment]
Solved by #84
