### ISSUE TITLE
Weekly Digest/Progress Summary up to May 25

### ISSUE THREAD

**Issue by jimdale** [camelot-project/frontend#95]
Below is a brief summary of the most important improvements in the 10 days since the workshop - let me know if I left out anything important:

DIGEST WEEK 1:

Database: 
(i) Discussed whether ADS/DOI info should be a prerequisite for submission to the database and concluded that it should be
(ii) New data tables by CaraBattersby, SimonGLover, MarkHeyer, AndreaGiannetti, BenoitCommercon, DanielWalker, TonyWong

Plotting:
(i) Axis label symbology fixed
(ii) Default plot ranges fixed
(iii) Discussed how to plot simulation tracks. Rendered contours popular, although would require extensive rewrite of plotting routines. Ways to plot tracks as lines of varying thickness also suggested, with points of different size at start and finish to indicate time’s arrow

Webpage: 
(i) Background image made static
(ii) Sim/Obs, Gal/Extragal buttons changed to radio buttons
(iii) Added mandatory email address requirement to submit form
(iv) Added ADS URL/DOI to submit form

**Comment by keflavich** [comment]
Moved to https://github.com/camelot-project/frontend/wiki/Weekly-Digest-%231
